AWSTemplateFormatVersion: "2010-09-09"
Description: "Movies API: Lambdas (ECR) + API Gateway REST + API Key + CORS"

Parameters:
  DDBTableName:
    Type: String
    Default: "MoviesTable"
    Description: "Nombre de la tabla DynamoDB existente"

Resources:
  # =========================
  # Lambdas (misma imagen) x5
  # =========================
  ListMoviesFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: movies-list
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/movie-app-lambda:latest"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 15
      MemorySize: 256
      Architectures: [ x86_64 ]
      Environment:
        Variables:
          HANDLER_NAME: list
          DDB_TABLE_NAME: !Ref DDBTableName

  GetMovieFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: movies-get
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/movie-app-lambda:latest"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 15
      MemorySize: 256
      Architectures: [ x86_64 ]
      Environment:
        Variables:
          HANDLER_NAME: get
          DDB_TABLE_NAME: !Ref DDBTableName

  CreateMovieFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: movies-create
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/movie-app-lambda:latest"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 15
      MemorySize: 256
      Architectures: [ x86_64 ]
      Environment:
        Variables:
          HANDLER_NAME: create
          DDB_TABLE_NAME: !Ref DDBTableName

  UpdateMovieFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: movies-update
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/movie-app-lambda:latest"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 15
      MemorySize: 256
      Architectures: [ x86_64 ]
      Environment:
        Variables:
          HANDLER_NAME: update
          DDB_TABLE_NAME: !Ref DDBTableName

  DeleteMovieFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: movies-delete
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/movie-app-lambda:latest"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 15
      MemorySize: 256
      Architectures: [ x86_64 ]
      Environment:
        Variables:
          HANDLER_NAME: delete
          DDB_TABLE_NAME: !Ref DDBTableName

  # =========================
  # Log groups (retención corta)
  # =========================
  ListMoviesLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ListMoviesFn}"
      RetentionInDays: 7

  GetMovieLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetMovieFn}"
      RetentionInDays: 7

  CreateMovieLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CreateMovieFn}"
      RetentionInDays: 7

  UpdateMovieLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${UpdateMovieFn}"
      RetentionInDays: 7

  DeleteMovieLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DeleteMovieFn}"
      RetentionInDays: 7

  # =========================
  # Permisos de invocación desde API Gateway
  # =========================
  PermList:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListMoviesFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*"

  PermGet:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetMovieFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*"

  PermCreate:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateMovieFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*"

  PermUpdate:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UpdateMovieFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*"

  PermDelete:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteMovieFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*"

  # =========================
  # API Gateway REST + CORS + API Key
  # =========================
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: movies-lambda-api
      EndpointConfiguration: { Types: [ REGIONAL ] }
      Description: "API Movies sobre Lambdas con ECR"

  MoviesRes:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: movies

  MovieIdRes:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref MoviesRes
      PathPart: "{id}"

  # OPTIONS /movies
  OptionsMovies:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MoviesRes
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates: { application/json: '{"statusCode": 200}' }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'content-type,x-api-key,accept'"
            ResponseTemplates: { application/json: "" }
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true

  # OPTIONS /movies/{id}
  OptionsMovieId:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MovieIdRes
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates: { application/json: '{"statusCode": 200}' }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'content-type,x-api-key,accept'"
            ResponseTemplates: { application/json: "" }
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true

  # Métodos /movies
  GetMoviesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MoviesRes
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListMoviesFn.Arn}/invocations"

  PostMoviesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MoviesRes
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateMovieFn.Arn}/invocations"

  # Métodos /movies/{id}
  GetMovieMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MovieIdRes
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters: { "method.request.path.id": true }
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMovieFn.Arn}/invocations"

  PutMovieMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MovieIdRes
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters: { "method.request.path.id": true }
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateMovieFn.Arn}/invocations"

  DeleteMovieMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref MovieIdRes
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters: { "method.request.path.id": true }
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteMovieFn.Arn}/invocations"

  # CORS en respuestas de error
  GWResp4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref RestApi
      ResponseType: DEFAULT_4XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'content-type,x-api-key,accept'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  GWResp5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref RestApi
      ResponseType: DEFAULT_5XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'content-type,x-api-key,accept'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  # Despliegue API
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetMoviesMethod
      - PostMoviesMethod
      - GetMovieMethod
      - PutMovieMethod
      - DeleteMovieMethod
      - OptionsMovies
      - OptionsMovieId
      - GWResp4XX
      - GWResp5XX
    Properties:
      RestApiId: !Ref RestApi

  StageProd:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod

  # API Key SIN StageKeys
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: movies-api-key-lambda
      Enabled: true

  # UsagePlan con referencia al Stage
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: StageProd
    Properties:
      UsagePlanName: movies-usage
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: !Ref StageProd

  # Asocia la API Key al Usage Plan
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  ApiBaseUrl:
    Description: "Base URL de la API"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  MoviesUrl:
    Description: "Endpoint /movies"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/movies"
  ApiKeyId:
    Description: "ID de la API Key"
    Value: !Ref ApiKey