from typing import Protocol, TypeVar

T = TypeVar("T")
TId = TypeVar("TId")

class Repository(Protocol[T, TId]):
    def get_all(self, q: str | None = None) -> list[T]: ...

    def get(self, item_id: TId) -> T | None: ...

    def add(self, data: T) -> T: ...

    def update(self, data: T) -> T | None: ...

    def delete(self, item_id: TId) -> bool: ...